using System;
using System.Threading.Tasks;
using PactNet;
using PactNet.Verifier;
using Xunit;

namespace Disbursement.IntegrationTests.Contract
{
    public class DisbursementApiProviderVerification
    {
        [Fact]
        public void Ensure_DisbursementApi_Honours_Consumer_Pact()
        {
            // Path to the pact file generated by the consumer
            var pactFile = "../pacts/consumer-disbursementapi.json";

            var verifier = new PactVerifier(new PactVerifierConfig
            {
                Outputters = new[] { new XUnitOutput(_output.WriteLine()) }
            });

            verifier
                .ServiceProvider("DisbursementApi", new Uri("http://localhost:80"))
                .WithFileSource(new FileInfo(pactFile))
                .Verify();
        }
    }

    // Helper for xUnit output
    public class XUnitOutput : PactNet.Infrastructure.Outputters.IOutput
    {
        private readonly Action<string> _output;
        public XUnitOutput(Action<string> output) => _output = output;
        public void WriteLine(string line) => _output(line);
    }
}
