name: Provider Contract Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout pact-contracts repository
        uses: actions/checkout@v4
        with:
          repository: suryamani-tw/pact-contracts
          path: pact-contracts

      - name: Prepare pact directories and copy files
        run: |
          mkdir -p ./pacts/api ./pacts/message
          cp pact-contracts/pacts/api/*.json ./pacts/api/ || echo "No API pact files found."
          cp pact-contracts/pacts/messages/*.json ./pacts/message/ || echo "No message pact files found."
        continue-on-error: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run contract tests
        run: dotnet test tests/Contract/Disbursement.ContractTests.csproj --no-build --verbosity normal
