name: Provider Contract Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    env:
      API_URL: http://localhost:5062
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout pact-contracts repository
        uses: actions/checkout@v4
        with:
          repository: suryamani-tw/pact-contracts
          path: pact-contracts

      - name: Prepare pact directories and copy files
        run: |
          mkdir -p ./pacts/api ./pacts/messages
          cp pact-contracts/pacts/api/*.json ./pacts/api/
          cp pact-contracts/pacts/messages/*.json ./pacts/messages/

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Start Disbursement API
        run: |
          dotnet run --project src/Disbursement.Api/Disbursement.Api.csproj --urls=${{ env.API_URL }} &
          sleep 10

      - name: Run contract tests
        run: dotnet test tests/ContractTests/Disbursement.ContractTests.csproj --no-build --verbosity normal
